In [28]:
import numpy as np

def pagerank_original(adj_matrix, damping_factor=0.85, epsilon=1e-8, max_iterations=100):
    """
    Compute PageRank using the power iteration method.

    Parameters:
    - adj_matrix: The adjacency matrix representing the link structure of the web graph.
    - damping_factor: The probability of following a link (typically set to 0.85).
    - epsilon: Convergence threshold.
    - max_iterations: Maximum number of iterations.

    Returns:
    - A vector representing the PageRank scores for each node.
    """
    # Input validation
    if not isinstance(adj_matrix, np.ndarray) or adj_matrix.ndim != 2 or adj_matrix.shape[0] != adj_matrix.shape[1]:
        raise ValueError("Input must be a square numpy array representing the adjacency matrix of a graph.")

    n = len(adj_matrix)
    print(n)
    # Initialize PageRank scores
    pagerank_scores = np.ones(n) / n

    for _ in range(max_iterations):
        prev_pagerank_scores = pagerank_scores.copy()

        # Perform the power iteration
        pagerank_scores = (1 - damping_factor) / n + damping_factor * np.dot(adj_matrix, pagerank_scores)
        print(pagerank_scores)

        # Check for convergence
        if np.linalg.norm(pagerank_scores - prev_pagerank_scores, 1) < epsilon:
           print("Converged--breaking\n")
           break


    # Normalize the scores to [0, 1]
    min_score = np.min(pagerank_scores)
    print(min_score)
    max_score = np.max(pagerank_scores)
    print(max_score)
    normalized_scores = (pagerank_scores - min_score) / (max_score - min_score)

    return normalized_scores

#M = np.array([[0, 1, 1], [1, 0, 0], [1, 1, 0]])
M = np.array([
    [0, 1, 1, 0, 0],
    [0, 0, 1, 1, 0],
    [0, 0, 0, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 1, 0, 0, 0]
])
normalized_scores = pagerank_original(M)
print("Normalized PageRank Scores:", normalized_scores)


5
[0.37 0.37 0.37 0.37 0.37]
[0.659 0.659 0.659 0.659 0.659]
[1.1503 1.1503 1.1503 1.1503 1.1503]
[1.98551 1.98551 1.98551 1.98551 1.98551]
[3.405367 3.405367 3.405367 3.405367 3.405367]
[5.8191239 5.8191239 5.8191239 5.8191239 5.8191239]
[9.92251063 9.92251063 9.92251063 9.92251063 9.92251063]
[16.89826807 16.89826807 16.89826807 16.89826807 16.89826807]
[28.75705572 28.75705572 28.75705572 28.75705572 28.75705572]
[48.91699473 48.91699473 48.91699473 48.91699473 48.91699473]
[83.18889103 83.18889103 83.18889103 83.18889103 83.18889103]
[141.45111476 141.45111476 141.45111476 141.45111476 141.45111476]
[240.49689508 240.49689508 240.49689508 240.49689508 240.49689508]
[408.87472164 408.87472164 408.87472164 408.87472164 408.87472164]
[695.1170268 695.1170268 695.1170268 695.1170268 695.1170268]
[1181.72894555 1181.72894555 1181.72894555 1181.72894555 1181.72894555]
[2008.96920744 2008.96920744 2008.96920744 2008.96920744 2008.96920744]
[3415.27765265 3415.27765265 3415.27765265 3415.2

<ipython-input-28-b5e73f0f9906>:43: RuntimeWarning: invalid value encountered in divide
  normalized_scores = (pagerank_scores - min_score) / (max_score - min_score)


In [ ]:
# wikipedia
import numpy as np

def pagerank(M, num_iterations: int = 100, d: float = 0.85):
    """PageRank algorithm with explicit number of iterations. Returns ranking of nodes (pages) in the adjacency matrix.

    Parameters
    ----------
    M : numpy array
        adjacency matrix where M_i,j represents the link from 'j' to 'i', such that for all 'j'
        sum(i, M_i,j) = 1
    num_iterations : int, optional
        number of iterations, by default 100
    d : float, optional
        damping factor, by default 0.85

    Returns
    -------
    numpy array
        a vector of ranks such that v_i is the i-th rank from [0, 1],
        v sums to 1

    """
    N = M.shape[1]
    v = np.ones(N) / N
    print(v)
    M_hat = (d * M + (1 - d) / N)
    for i in range(num_iterations):
        v = M_hat @ v
        print(v)
    return v

M = np.array([[0, 1, 1], [1, 0, 0], [1, 1, 0]])

v = pagerank(M, 100, 0.85)
print(v)

In [5]:
import numpy as np

def pagerank(M, num_iterations: int = 100, d: float = 0.85):
    """PageRank algorithm with explicit number of iterations. Returns ranking of nodes (pages) in the adjacency matrix.

    Parameters
    ----------
    M : numpy array
        adjacency matrix where M_i,j represents the link from 'j' to 'i', such that for all 'j'
        sum(i, M_i,j) = 1
    num_iterations : int, optional
        number of iterations, by default 100
    d : float, optional
        damping factor, by default 0.85

    Returns
    -------
    numpy array
        a vector of ranks such that v_i is the i-th rank from [0, 1],
        v sums to 1

    """
    N = M.shape[1]
    v = np.ones(N) / N
    for i in range(num_iterations):
        v = d * (M @ v) + (1 - d) / N
    return v

M = np.array([[0, 1, 1], [1, 0, 0], [1, 1, 0]])

v = pagerank(M, 100, 0.85)
print(v)


[3.78481722e+13 2.33914568e+13 3.78481722e+13]


In [25]:
import numpy as np

def pagerank(M, num_iterations: int = 100, d: float = 0.85):
    """PageRank algorithm with explicit number of iterations. Returns normalized ranking of nodes (pages) in the adjacency matrix.

    Parameters
    ----------
    M : numpy array
        adjacency matrix where M_i,j represents the link from 'j' to 'i', such that for all 'j'
        sum(i, M_i,j) = 1
    num_iterations : int, optional
        number of iterations, by default 100
    d : float, optional
        damping factor, by default 0.85

    Returns
    -------
    numpy array
        a vector of normalized ranks such that v_i is the i-th rank from [0, 1]
    """
    N = M.shape[1]
    v = np.ones(N) / N
    for i in range(num_iterations):
        v = d * (M @ v) + (1 - d) / N

    # Normalize the scores to [0, 1]
    min_score = np.min(v)
    max_score = np.max(v)
    normalized_scores = (v - min_score) / (max_score - min_score)

    return normalized_scores

#M = np.array([[0, 1, 1], [1, 0, 0], [1, 1, 0]])
M = np.array([
    [0, 1, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0]
])
normalized_scores = pagerank(M, 100, 0.85)
print("Normalized PageRank Scores:", normalized_scores)


Normalized PageRank Scores: [1.         0.         0.19068271 0.41643191 0.68370121]
